"""table group

Revision ID: 0c00357a9005
Revises: 19058723e988
Create Date: 2025-09-05 21:53:42.165070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from src.models import *



# revision identifiers, used by Alembic.
revision: str = '0c00357a9005'
down_revision: Union[str, Sequence[str], None] = '19058723e988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    with op.batch_alter_table("post") as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("post", 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post") as batch_op:
        batch_op.drop_constraint('post', 'group_id', type_='foreignkey')
        batch_op.drop_column('group_id')
    op.drop_table('user_group')
    op.drop_table('group')
    # ### end Alembic commands ###
